# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# http://jekyllrb.com/docs/upgrading/2-to-3/#relative-permalink-support-removed
# relative_permalinks: true

# Setup
title:               Jan Carlo Viray
tagline:             'React &middot; Angular &middot; Node &middot; Go &middot; SQL &middot; NoSQL &middot; Cloud &middot; Entrepreneurship'
description:         'Official site of Jan Carlo Viray. Lead Senior Front-End Engineer in Los Angeles and Orange County, California. Angular. React. Node. Postgres. AWS. Docker. Full Stack.'
url:                 http://www.jancarloviray.com
shorturl:            www.jancarloviray.com
baseurl:             http://jancarloviray.github.io
paginate:            20
timezone:            America/Los_Angeles

# About/contact
author:
  name:              Jan Carlo Viray
  quote:             'A year from now you&rsquo;ll wish you started today &mdash; <cite>Karen Lamb</cite>'
  url:               https://twitter.com/jancarloviray
  email:             virayjancarlo@yahoo.com
  twitter:           https://twitter.com/jancarloviray
  linkedin:          https://www.linkedin.com/in/jancarloviray
  github:            https://github.com/jancarloviray

github:
  repo:              https://github.com/jancarloviray/jancarloviray.github.io

pages_list:
  About: '/about/'
  Archive: '/archive/'
  #Feed: '/atom.xml'

# Custom vars
version:             1.0.0
